env: "dev"
app:
  name: "simple-rest"
  version: "1.0.0"

http:
  port: "8082"

logger:
  log_level: "debug"
  rollbar_env: "simple-rest"

postgres:
  host: "localhost"
  db_name: "postgres"
  user: "postgres"
  password: "postgres"
  ssl_mode: "disable"
  port: 5432
  schema: "top-up"

redis:
  addr: "localhost:6379"
  password: "password123"
  db: 0

jwt:
  secret: "simple-rest-jwt-secret"

kafka:
  broker: "localhost:9092"
  group_id: "MkU3OEVBNTcwNTJENDM2Qk"
  order_group:
    confirm_topic: "my-topic"
    group_id: ""
