// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/card-detail": {
            "get": {
                "description": "Get card details grouped by provider",
                "tags": [
                    "card-detail"
                ],
                "summary": "Get card details grouped by provider",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.SkusGroupByProvider"
                        }
                    }
                }
            }
        },
        "/card-detail/{providerCode}": {
            "get": {
                "description": "Get card details by provider code",
                "tags": [
                    "card-detail"
                ],
                "summary": "Get card details by provider code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider code",
                        "name": "providerCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/top-up-api_internal_schema.SkuResponse"
                            }
                        }
                    }
                }
            }
        },
        "/order/confirm": {
            "post": {
                "description": "Confirm order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Confirm order",
                "parameters": [
                    {
                        "description": "Order confirm request",
                        "name": "orderConfirmRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderConfirmRequest"
                        }
                    }
                }
            }
        },
        "/order/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Create order",
                "parameters": [
                    {
                        "description": "Order request",
                        "name": "orderRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderResponse"
                        }
                    }
                }
            }
        },
        "/order/update-status": {
            "patch": {
                "description": "Update order status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "parameters": [
                    {
                        "description": "Order update request",
                        "name": "orderUpdateRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.Response"
                        }
                    }
                }
            }
        },
        "/provider": {
            "get": {
                "description": "Get providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "provider"
                ],
                "summary": "Get providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/top-up-api_internal_schema.ProviderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/purchase-history/{user_id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get purchase history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase-history"
                ],
                "summary": "Get purchase history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.PaginationResponse"
                        }
                    }
                }
            }
        },
        "/user/create": {
            "post": {
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User create details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User login request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.Response"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "top-up-api_internal_model.PurchaseHistoryStatus": {
            "type": "string",
            "enum": [
                "pending",
                "confirm",
                "success",
                "failed"
            ],
            "x-enum-varnames": [
                "PurchaseHistoryStatusPending",
                "PurchaseHistoryStatusConfirm",
                "PurchaseHistoryStatusSuccess",
                "PurchaseHistoryStatusFailed"
            ]
        },
        "top-up-api_internal_schema.OrderConfirmRequest": {
            "type": "object",
            "properties": {
                "cash_back_value": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistoryStatus"
                },
                "total_price": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.OrderRequest": {
            "type": "object",
            "properties": {
                "phone_number": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.OrderResponse": {
            "type": "object",
            "properties": {
                "cash_back_value": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "sku": {
                    "$ref": "#/definitions/top-up-api_internal_schema.SkuResponse"
                },
                "status": {
                    "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistoryStatus"
                },
                "total_price": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.OrderUpdateRequest": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistoryStatus"
                }
            }
        },
        "top-up-api_internal_schema.Pagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.PaginationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/top-up-api_internal_schema.Pagination"
                }
            }
        },
        "top-up-api_internal_schema.ProviderInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_schema.ProviderResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_schema.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_schema.SkuMiniatureResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "provider": {}
            }
        },
        "top-up-api_internal_schema.SkuResponse": {
            "type": "object",
            "properties": {
                "cash_back": {},
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "provider": {
                    "$ref": "#/definitions/top-up-api_internal_schema.ProviderInfo"
                }
            }
        },
        "top-up-api_internal_schema.SkusGroupByProvider": {
            "type": "object",
            "properties": {
                "provider_code": {
                    "type": "string"
                },
                "provider_logo_url": {
                    "type": "string"
                },
                "provider_name": {
                    "type": "string"
                },
                "sku": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/top-up-api_internal_schema.SkuMiniatureResponse"
                    }
                }
            }
        },
        "top-up-api_internal_schema.UserCreateRequest": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password",
                "phone_number"
            ],
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 10
                }
            }
        },
        "top-up-api_internal_schema.UserLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "phone_number"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 10
                }
            }
        },
        "top-up-api_internal_schema.UserProfileResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "cash_back": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Enter the token with the ` + "`" + `Bearer` + "`" + ` prefix, e.g., ` + "`" + `Bearer \u003ctoken\u003e` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
