// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: provider.proto

package providerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	TotalPrice    int64                  `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	CallBackUrl   string                 `protobuf:"bytes,5,opt,name=call_back_url,json=callBackUrl,proto3" json:"call_back_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProcessRequest) Reset() {
	*x = OrderProcessRequest{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProcessRequest) ProtoMessage() {}

func (x *OrderProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProcessRequest.ProtoReflect.Descriptor instead.
func (*OrderProcessRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

func (x *OrderProcessRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderProcessRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *OrderProcessRequest) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderProcessRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderProcessRequest) GetCallBackUrl() string {
	if x != nil {
		return x.CallBackUrl
	}
	return ""
}

type OrderProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProcessResponse) Reset() {
	*x = OrderProcessResponse{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProcessResponse) ProtoMessage() {}

func (x *OrderProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProcessResponse.ProtoReflect.Descriptor instead.
func (*OrderProcessResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *OrderProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OrderProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\x05order\"\xae\x01\n" +
	"\x13OrderProcessRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x03R\n" +
	"totalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\"\n" +
	"\rcall_back_url\x18\x05 \x01(\tR\vcallBackUrl\"F\n" +
	"\x14OrderProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Z\n" +
	"\x0fProviderService\x12G\n" +
	"\fProcessOrder\x12\x1a.order.OrderProcessRequest\x1a\x1b.order.OrderProcessResponseB\x1bZ\x19proto/provider;providerpbb\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_provider_proto_goTypes = []any{
	(*OrderProcessRequest)(nil),  // 0: order.OrderProcessRequest
	(*OrderProcessResponse)(nil), // 1: order.OrderProcessResponse
}
var file_provider_proto_depIdxs = []int32{
	0, // 0: order.ProviderService.ProcessOrder:input_type -> order.OrderProcessRequest
	1, // 1: order.ProviderService.ProcessOrder:output_type -> order.OrderProcessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
