// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/card-detail/{providerCode}": {
            "get": {
                "description": "Get card details by provider code",
                "tags": [
                    "card-detail"
                ],
                "summary": "Get card details by provider code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider code",
                        "name": "providerCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/top-up-api_internal_schema.CardDetailResponse"
                            }
                        }
                    }
                }
            }
        },
        "/order/confirm": {
            "post": {
                "description": "Confirm order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Confirm order",
                "parameters": [
                    {
                        "description": "Order confirm request",
                        "name": "orderConfirmRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderConfirmRequest"
                        }
                    }
                }
            }
        },
        "/order/create": {
            "post": {
                "description": "Create order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Create order",
                "parameters": [
                    {
                        "description": "Order request",
                        "name": "orderRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.OrderResponse"
                        }
                    }
                }
            }
        },
        "/provider": {
            "get": {
                "description": "Get providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "provider"
                ],
                "summary": "Get providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/top-up-api_internal_schema.ProviderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/purchase-history/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get purchase history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase-history"
                ],
                "summary": "Get purchase history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistory"
                            }
                        }
                    }
                }
            }
        },
        "/user/create": {
            "post": {
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User create details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User login request",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserLoginDetail"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/top-up-api_internal_schema.UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "top-up-api_internal_model.CardDetail": {
            "type": "object",
            "properties": {
                "card_price": {
                    "$ref": "#/definitions/top-up-api_internal_model.CardPrice"
                },
                "card_price_code": {
                    "type": "string"
                },
                "cash_back": {
                    "$ref": "#/definitions/top-up-api_internal_model.CashBack"
                },
                "cash_back_code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "provider": {
                    "$ref": "#/definitions/top-up-api_internal_model.Provider"
                },
                "provider_code": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_model.CardPrice": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_model.CashBack": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/top-up-api_internal_model.CashBackType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_model.CashBackType": {
            "type": "string",
            "enum": [
                "percentage",
                "fixed"
            ],
            "x-enum-varnames": [
                "CashBackTypePercentage",
                "CashBackTypeFixed"
            ]
        },
        "top-up-api_internal_model.Provider": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_model.PurchaseHistory": {
            "type": "object",
            "properties": {
                "card_detail": {
                    "$ref": "#/definitions/top-up-api_internal_model.CardDetail"
                },
                "card_detail_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistoryStatus"
                },
                "total_price": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/top-up-api_internal_model.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_model.PurchaseHistoryStatus": {
            "type": "string",
            "enum": [
                "pending",
                "success",
                "failed"
            ],
            "x-enum-varnames": [
                "PurchaseHistoryStatusPending",
                "PurchaseHistoryStatusSuccess",
                "PurchaseHistoryStatusFailed"
            ]
        },
        "top-up-api_internal_model.User": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "cash_back": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "purchase_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistory"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_schema.CardDetailResponse": {
            "type": "object",
            "properties": {
                "card_price": {
                    "$ref": "#/definitions/top-up-api_internal_schema.CardPriceResponse"
                },
                "cash_back": {},
                "id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.CardPriceResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.OrderConfirmRequest": {
            "type": "object",
            "properties": {
                "card_detail": {
                    "$ref": "#/definitions/top-up-api_internal_schema.CardDetailResponse"
                },
                "cash_back_value": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistoryStatus"
                },
                "total_price": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.OrderRequest": {
            "type": "object",
            "properties": {
                "card_detail_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.OrderResponse": {
            "type": "object",
            "properties": {
                "card_detail": {
                    "$ref": "#/definitions/top-up-api_internal_schema.CardDetailResponse"
                },
                "cash_back_value": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/top-up-api_internal_model.PurchaseHistoryStatus"
                },
                "total_price": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "top-up-api_internal_schema.ProviderResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_schema.UserCreateRequest": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password",
                "phone_number"
            ],
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 10
                }
            }
        },
        "top-up-api_internal_schema.UserLoginDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "top-up-api_internal_schema.UserLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "phone_number"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 10
                }
            }
        },
        "top-up-api_internal_schema.UserProfileResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "cash_back": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Enter the token with the ` + "`" + `Bearer` + "`" + ` prefix, e.g., ` + "`" + `Bearer \u003ctoken\u003e` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
