definitions:
  top-up-api_internal_model.PurchaseHistoryStatus:
    enum:
    - pending
    - confirm
    - success
    - failed
    type: string
    x-enum-varnames:
    - PurchaseHistoryStatusPending
    - PurchaseHistoryStatusConfirm
    - PurchaseHistoryStatusSuccess
    - PurchaseHistoryStatusFailed
  top-up-api_internal_model.SupplierStatus:
    enum:
    - active
    - inactive
    type: string
    x-enum-varnames:
    - SupplierStatusActive
    - SupplierStatusInactive
  top-up-api_internal_schema.OrderConfirmRequest:
    properties:
      cash_back_value:
        type: integer
      order_id:
        type: integer
      phone_number:
        type: string
      sku_id:
        type: integer
      status:
        $ref: '#/definitions/top-up-api_internal_model.PurchaseHistoryStatus'
      total_price:
        type: integer
      user_id:
        type: integer
    type: object
  top-up-api_internal_schema.OrderRequest:
    properties:
      phone_number:
        type: string
      sku_id:
        type: integer
      user_id:
        type: integer
    type: object
  top-up-api_internal_schema.OrderResponse:
    properties:
      cash_back_value:
        type: integer
      order_id:
        type: integer
      phone_number:
        type: string
      rand_provider_weight:
        type: integer
      sku:
        $ref: '#/definitions/top-up-api_internal_schema.SkuResponse'
      status:
        $ref: '#/definitions/top-up-api_internal_model.PurchaseHistoryStatus'
      total_price:
        type: integer
      user_id:
        type: integer
    type: object
  top-up-api_internal_schema.OrderUpdateRequest:
    properties:
      order_id:
        type: integer
      phone_number:
        type: string
      status:
        $ref: '#/definitions/top-up-api_internal_model.PurchaseHistoryStatus'
    type: object
  top-up-api_internal_schema.Pagination:
    properties:
      current_page:
        type: integer
      total_count:
        type: integer
      total_page:
        type: integer
    type: object
  top-up-api_internal_schema.PaginationResponse:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
      message:
        type: string
      pagination:
        $ref: '#/definitions/top-up-api_internal_schema.Pagination'
    type: object
  top-up-api_internal_schema.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
      message:
        type: string
    type: object
  top-up-api_internal_schema.SkuMiniatureResponse:
    properties:
      cashback: {}
      id:
        type: integer
      price:
        type: integer
    type: object
  top-up-api_internal_schema.SkuResponse:
    properties:
      cash_back: {}
      id:
        type: integer
      price:
        type: integer
      supplier:
        $ref: '#/definitions/top-up-api_internal_schema.SupplierInfo'
    type: object
  top-up-api_internal_schema.SkusGroupBySupplier:
    properties:
      sku:
        items:
          $ref: '#/definitions/top-up-api_internal_schema.SkuMiniatureResponse'
        type: array
      supplier_code:
        type: string
      supplier_logo_url:
        type: string
      supplier_name:
        type: string
    type: object
  top-up-api_internal_schema.SupplierInfo:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  top-up-api_internal_schema.SupplierResponse:
    properties:
      code:
        type: string
      logo:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/top-up-api_internal_model.SupplierStatus'
    type: object
info:
  contact: {}
paths:
  /order/confirm:
    post:
      consumes:
      - application/json
      description: Confirm order
      parameters:
      - description: Order confirm request
        in: body
        name: orderConfirmRequest
        required: true
        schema:
          $ref: '#/definitions/top-up-api_internal_schema.OrderConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/top-up-api_internal_schema.OrderConfirmRequest'
      summary: Confirm order
      tags:
      - order
  /order/create:
    post:
      consumes:
      - application/json
      description: Create order
      parameters:
      - description: Order request
        in: body
        name: orderRequest
        required: true
        schema:
          $ref: '#/definitions/top-up-api_internal_schema.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/top-up-api_internal_schema.OrderResponse'
      security:
      - Bearer: []
      summary: Create order
      tags:
      - order
  /order/update-status:
    patch:
      consumes:
      - application/json
      description: Update order status
      parameters:
      - description: Order update request
        in: body
        name: orderUpdateRequest
        required: true
        schema:
          $ref: '#/definitions/top-up-api_internal_schema.OrderUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/top-up-api_internal_schema.Response'
      tags:
      - order
  /purchase-history/{user_id}:
    get:
      consumes:
      - application/json
      description: Get purchase history
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/top-up-api_internal_schema.PaginationResponse'
      security:
      - Bearer: []
      summary: Get purchase history
      tags:
      - purchase-history
  /sku:
    get:
      description: Get card details grouped by supplier
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/top-up-api_internal_schema.SkusGroupBySupplier'
      summary: Get card details grouped by supplier
      tags:
      - sku
  /sku/{supplierCode}:
    get:
      description: Get sku details by supplier code
      parameters:
      - description: Supplier code
        in: path
        name: supplierCode
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/top-up-api_internal_schema.SkuResponse'
            type: array
      summary: Get sku details by supplier code
      tags:
      - sku
  /supplier:
    get:
      consumes:
      - application/json
      description: Get supplier
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/top-up-api_internal_schema.SupplierResponse'
            type: array
      summary: Get supplier
      tags:
      - supplier
securityDefinitions:
  Bearer:
    description: Enter the token with the `Bearer` prefix, e.g., `Bearer <token>`
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
